"""LangGraph state definitions for the NL2SQL Data Agent."""

from typing import Annotated, NotRequired, TypedDict

from langchain_core.messages import AnyMessage
from langgraph.graph import add_messages

from data_agent.models.outputs import QueryResult, SQLValidationOutput


class InputState(TypedDict):
    """User-provided input to invoke the agent.

    Attributes:
        question: Natural language question to answer.
        datasource_name: Name of the datasource to query.
    """

    question: str
    datasource_name: str


class OutputState(TypedDict):
    """Agent output returned after processing.

    Attributes:
        generated_sql: The SQL query generated from the question.
        final_response: Human-readable response summarizing the results.
        result: Query execution results as QueryResult.
        error: Error message if processing failed.
        datasource_name: Name of the agent/datasource that handled the query.
        rewritten_question: The question after query rewriting (if different from original).
        messages: Accumulated LLM conversation messages (for debugging).
        visualization_image: Base64-encoded PNG image of chart (if visualization was requested).
        visualization_code: Generated Python code for visualization.
        visualization_error: Error message if visualization generation failed.
    """

    generated_sql: str
    final_response: str
    result: QueryResult | None
    error: str | None
    datasource_name: NotRequired[str]
    rewritten_question: NotRequired[str]
    messages: NotRequired[list[AnyMessage]]
    visualization_image: NotRequired[str | None]
    visualization_code: NotRequired[str | None]
    visualization_error: NotRequired[str | None]


class AgentState(TypedDict):
    """Internal state passed between LangGraph nodes.

    Combines input, intermediate processing state, and output fields.
    Uses LangGraph's add_messages reducer for message accumulation.

    Attributes:
        question: Natural language question from user.
        datasource_name: Target datasource identifier.
        dialect: SQL dialect for validation (postgres, tsql, cosmosdb, etc.).
        schema_context: Database schema information for SQL generation.
        messages: Accumulated LLM conversation messages.
        generated_sql: SQL query generated by the LLM.
        result: Query execution results as QueryResult.
        final_response: Human-readable summary of results.
        error: Error message if processing failed.
        retry_count: Current retry attempt number.
        rewritten_question: The question after query rewriting (if different from original).
        validation_result: SQL validation output with status, errors, and warnings.
        visualization_requested: Whether the user requested a visualization (set by generate_sql).
        visualization_image: Base64-encoded PNG image of generated chart.
        visualization_code: Generated Python code for visualization.
        visualization_error: Error message if visualization generation failed.
    """

    question: str
    datasource_name: str
    dialect: NotRequired[str]
    schema_context: NotRequired[str]
    messages: Annotated[list[AnyMessage], add_messages]
    generated_sql: NotRequired[str]
    result: NotRequired[QueryResult | None]
    final_response: NotRequired[str]
    error: NotRequired[str | None]
    retry_count: NotRequired[int]
    rewritten_question: NotRequired[str]
    validation_result: NotRequired[SQLValidationOutput | None]
    visualization_requested: NotRequired[bool]
    visualization_image: NotRequired[str | None]
    visualization_code: NotRequired[str | None]
    visualization_error: NotRequired[str | None]
